language: go

go:
  - "1.9.4"
  - "1.11.x"

env:
  - GO111MODULE=on

before_script:
  - if [[ $(go version) = *1.9.4* ]]; then
    git clone https://github.com/golang/tools.git ./vendor/golang.org/x/tools;
    git -C ./vendor/golang.org/x/tools checkout 4c874b978acba4ecd4a257d3bb8829dd5de17be8;
    fi
